#!/bin/bash
# Creates a container for mariadb and mounts it to
# a volume on the docker host
# This method is less flexible than mounting to an
# explicit data container

CONTAINER="alarmservice_db_container"
IMAGE="mariadb:latest"

docker run -d \
    --name ${CONTAINER} \
    -e MYSQL_USER=mysql \
    -e MYSQL_PASSWORD=mysql \
    -e MYSQL_DATABASE=alarmservicedb \
    -e MYSQL_ROOT_PASSWORD=supersecret \
    -v ~/mariadb/alarmservicedb/data:/var/lib/mysql \
    -p 3301:3306 ${IMAGE}
