#!/bin/bash

DB_CONTAINER="dnam_db_container"
IMAGE="mariadb:latest"

docker run -d \
    --name ${DB_CONTAINER} \
    -e MYSQL_USER=admin \
    -e MYSQL_PASSWORD=admin \
    -e MYSQL_DATABASE=tnmdb \
    -e MYSQL_ROOT_PASSWORD=supersecret \
    -p 3301:3306 ${IMAGE}
